### ISSUE TITLE
Convert WebGL canvas to image byte array

### ISSUE THREAD

**Issue by JacobClinton** [BlazorExtensions/Canvas#109]
I am currently trying to find a way to convert a WebGL canvas into a byte array so that I can recreate the image later in my code. I've tried searching up how to do this in javascript and using 'toDataUrl' seems like the best way to go but the image returned is always blank (even when I set 'preserveDrawingBuffer' to true). I'm assuming it has something to do with Blazor's async calls but I really just don't know enough about this to be sure and Blazor.Extensions does not seem to have an accessible 'toDataUrl' method within their canvas.

Two questions really. Is it possible to convert a canvas to an image without JS using C# only? If not, how do I go about doing it with JS?

**Comment by mruch2** [comment]
I am having the same issue. Have you found a way to get this working? I am in need of it for my app.

**Comment by JacobClinton** [comment]
Apologies to anyone who's had the same problem, I was able to solve it but never got around to updating this issue. I'm going to do my best to explain my solution but it has been well over a year since I solved it so sorry if I don't remember all of the details. 

I've just checked and I have no references to 'preserveDrawingBuffer' in my code, so it seems it wasn't required. I created a 'CanvasToImage' method that I called at the very end of my 'LoadAnim' method. My 'LoadAnim' method sets the world and view matrices and then calls the following method: 
```
/// <summary>
/// Do the batch process of drawing the canvas
/// </summary>
/// <returns></returns>
public static async Task DrawCanvas(this WebGLContext context, int vertexCount)
{
    await context.BeginBatchAsync();
    await context.ClearAsync(BufferBits.COLOR_BUFFER_BIT);

    await context.DrawElementsAsync(Primitive.TRIANGLES, vertexCount, DataType.UNSIGNED_SHORT, 0);
    await context.EndBatchAsync();
}
```

My 'CanvasToImage' method calls the following javascript function:
```
function CanvasToImage() {
    var canvas = document.getElementsByTagName("canvas")[0];
    var imageData = canvas.toDataURL();

    return imageData;
}
```

The 'imageData' returned would construct one of the following: a blank white canvas, a partially completed image, or the full canvas image. There didn't seem to be a way of ensuring that the completed image was created each time so my solution was to keep trying to create the image until the full image was outputted. I noticed that, depending on the result, the size of the data string returned would vary wildly. After a fair amount of trial and error, I found that if the length of the image data URL was greater than 100,000 characters the converted image would be the desired one. This is how I ended up with the following method:

```
public async Task CanvasToImage()
{
    _image3DSrc = await JsRuntime.InvokeAsync<string>("CanvasToImage");

    if (_image3DSrc.Length < 100000)
        await LoadAnim(true);
    else
        _captureImage = false;
}
```

I understand that this is far from a perfect solution and there is a lot about how I am using WebGL that I still don't understand but I hope this might help point someone in the right direction. Obviously, if anyone comes up with a better approach please add it to this thread. Any problems, let me know and I'll do my best to answer them if I can.

**Comment by JacobClinton** [comment]
@mruch2 I hope you figured out a solution. Sorry, it took me so long to see this.

**Comment by mruch2** [comment]
@JacobClinton I found a pretty descent way of doing this. Since the Canvas webgl rendering is double buffered you have to catch the drawn to buffer before it finishes the batch. So What I did was this.

`
    private async callWithContext(context: any, method: string, args: any, canvas: HTMLCanvasElement): Promise<any> {
        const result = this.prototypes[method].apply(context, args != undefined ? args.map((value) => this.deserialize(method, value)) : []);

        if (method == 'createPattern') {
            const key = uuidv4();
            this.patterns.set(key, result);
            return key;
        }
        //console.log(method + " : " + this.SaveImageSnapshot);

        // save it at the end of the batch calls
        if (this.SaveImageSnapshot && method == 'drawArrays') {
            await this.saveImage(canvas);
        }

        return this.serialize(result);
    }`

Keep in mind that I consumed the entire project. My buddy and I converted it to WebGL2 and are currently extending it to add support for dynamic scene creation.

**Comment by JacobClinton** [comment]
@mruch2 Sounds interesting, thanks for your response. If I get a chance I might look further into it in the future.
