### ISSUE TITLE
Support for Blazor Canvas Extension in .NET MAUI?

### ISSUE THREAD

**Issue by bill-reiss** [BlazorExtensions/Canvas#113]
I know we are still a few months from release of .NET MAUI but I find the combination of MAUI and Blazor very exciting. Are there any plans to make the Canvas extension compatible with MAUI projects?

**Comment by RChrisCoble** [comment]
Part of the MAUI API's being delivered is "[Microsoft.Maui.Graphics](https://github.com/dotnet/Microsoft.Maui.Graphics)".  This doesn't have a dependency on Maui directly, so any .Net 6 application can use it.  Microsoft.Maui.Graphics has backend bindings for an HTML5 canvas just like this repo, along with support of call batching if running Blazor from the server.

My guess is this Canvas Blazor extension would no longer be needed as the support will be baked into .Net 6 directly.  Some MAUI controls being developed are already using the above repo, making them compatible with any platform supported by Microsoft.Maui.Graphics.  Exciting times.

**Comment by bill-reiss** [comment]
Wow this is really exciting thank you.

**Comment by Thaina** [comment]
@RChrisCoble So what is the future of this repo then? Would this be merged or moved into maui graphics in the future or it still stand alone for non maui app?

**Comment by RChrisCoble** [comment]
I have no idea what the future is.  It’s simply not necessary anymore.  

Note: I’m not an owner or maintainer in this repo or the Maui.graphics repo.  I’m just a random person.  :)

**Comment by Thaina** [comment]
Oh right. Still Thanks for your response

**Comment by galvesribeiro** [comment]
This is a great thing. If That library flies It would indeed be finally a good cross-platform drawing library and if it run properly with web assembly and also support pure native HTML5 Canvas, like we do here, it would make this lib unnecessary.

However, keep in mind that just by having "MAUI" on its name, already implies some sort of relation with the rest of the MAUI framework even if it says "it has no dependencies". I have no idea yet if it is a good or bad thing. We will see. If the time comes and that library overcomes this one, and it truly isn't dependent on any aspect on MAUI, I'm all up for deprecating this library.
