### ISSUE TITLE
BECanvasComponent could not be found

### ISSUE THREAD

**Issue by JD9999** [BlazorExtensions/Canvas#137]
I would like to use this package to draw a rectangle on an HTML canvas (I'm learning how to use Blazor, so starting small!)

I believe I have set up everything correctly. Here are the steps I followed:
- I added a default project using "dotnet new ShapeShifter -o ShapeShifter" 
- I installed the package using "dotnet add package Blazor.Extensions.Canvas"
- I added the "<script src="_content/Blazor.Extensions.Canvas/blazor.extensions.canvas.js"></script>" line at the end of my body text in the _Host.cshtml file
- I added "@using Blazor.Extensions.Canvas" to the end of my _Imports.razor

Then this is my Canvas.razor:

```
﻿@page "/canvas"

<PageTitle>Canvas</PageTitle>

<h1>Canvas</h1>

<BECanvas Width="200" Height="100" @ref="canvas"/>

@code{
	protected BECanvasComponent canvas;

	protected override void OnAfterRender(bool firstRender){
		Canvas2DContext context = canvas.CreateCanvas2D();
		context.SetFillStyle("green");
		context.FillRect(0, 0, 50, 50);
	}
}
```

When I try to build this with "dotnet watch", I get the following error: "error CS0246: The type or namespace name 'BECanvasComponent' could not be found (are you missing a using directive or an assembly reference?)"

How do I resolve this error?

**Comment by JacobClinton** [comment]
BECanvasComponent is located in 'Blazor.Extensions' not 'Blazor.Extensions.Canvas'. You should just need to add the following code to your _Imports.razor file.

`@using Blazor.Extensions`

I'd also recommend using an editor like Visual Studio 2022, as compile errors like this should really be picked up as your writing the code.

**Comment by JD9999** [comment]
Awesome! Thanks for that!
