### ISSUE TITLE
dependency to microsoft.aspnet.blazor 0.5.1.. but i can't downgrade

### ISSUE THREAD

**Issue by BasieP** [BlazorExtensions/Canvas#15]
we're now at 0.6, but i can't downgrade somehow to 0.5.1..

still haven't got the demo to work 👎 

How to fix this?

**Comment by galvesribeiro** [comment]
I've updated the package to 0.6.0.

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/4714040/46919824-7c893180-cfbb-11e8-9300-91c9fe9d6290.png">

The demo works. The new package should be published on nuget any minute. Please let me know if it still doesn't work for you.

**Comment by BasieP** [comment]
Blazing fast response!

Good job
