### ISSUE TITLE
Can Canvas2dContextManager.ts and InitializeCanvas.ts be removed?

### ISSUE THREAD

**Issue by zwcloud** [BlazorExtensions/Canvas#17]
How to use the Canvas API without referencing any js/ts project? If it is not possible for current __BlazorExtensions/Canvas__, how to achieve that?

**Comment by galvesribeiro** [comment]
Hello!

Can you clarify more what you are trying to achieve? 

The .JS part contains the typescript required to interop with the Canvas APIs on the browser. How would we do the interop without it?

**Comment by zwcloud** [comment]
I'm trying to create a simple C# binding of WebGL for blazor without any js code. And I found this repo.

What really needed is

    var canvas = document.createElement('canvas');
    document.body.appendChild(canvas);
    var gl = canvas.getContext('webgl');

and subsequent WebGL calls.

The js code above should be written in C#. For example,

    var canvas = (JSRuntime.Current as IJSInProcessRuntime).Invoke<object>("document.createElement", "canvas");
    //...

**Comment by galvesribeiro** [comment]
Okey... Now it make sense.

I agree with you that it may be possible. I just don't know how the object lifecycle will be. i.e. if both C# and JS GACs will not collect it while you are using it...

I would need to experiment with that... 

Did you made any tests doing that?

If that is the case, we can update the component to be that way and then include the webgl backend.

**Comment by jinqi166** [comment]
Blazor +  webgl   
That means I can write a H5 game use c# ！

**Comment by galvesribeiro** [comment]
There was a huge change on those contexts with recent PRs. Now it support WebGL as well. Please check the updated packages. We can re-open it if we still need changes. Thanks!
