### ISSUE TITLE
CreateCanvas2DAsync does not exist in BECanvasComponent 

### ISSUE THREAD

**Issue by ttosello** [BlazorExtensions/Canvas#39]
The samples provided on the project page as well as within the source do not work since CreateCanvas2DAsync does not exist in BECanvasComponent.

**Comment by galvesribeiro** [comment]
@ttosello you are probably missing the `using` statement in order to bring the extension method to the context. Look here:

https://github.com/BlazorExtensions/Canvas/blob/master/test/Blazor.Extensions.Canvas.Test.ClientSide/Pages/IndexComponent.cs#L1

Let me know if you still have issues.

**Comment by ttosello** [comment]
@using Blazor.Extensions  was required.


Trevor Tosello
Senior Software Architect

T: 1.416-706-7340
E: ttosello@blackriversc.com<mailto:ttosello@blackriversc.com>
U: http://www.blackriversc.com

**Comment by galvesribeiro** [comment]
Yeah, if you are not using a "codebehind" file like in the sample, indeed the `@using` on the component markup is required. Glad you found out. Thanks!
