### ISSUE TITLE
Adding BECanvas component causes build failure

### ISSUE THREAD

**Issue by ttosello** [BlazorExtensions/Canvas#40]
Adding BECanvas component to a razor page causes the following build error:

_Cannot implicitly convert type 'Microsoft.AspNetCore.Components.ElementReference' to 'Blazor.Extensions.BECanvasComponent'_

I am using .NET Core Preview 9

**Comment by snowchenlei** [comment]
I also encountered this error

**Comment by torgabor** [comment]
I've also ran into this issue. The problem is that Razor cannot find the `BECanvas` component, but for some reason, Intellisense doesn't seem to complain.
The solution is adding the appropriate using either to the class, or the `_Imports.razor` file.
Like this: `@using Blazor.Extensions.Canvas`

**Comment by rrMciLend** [comment]
I had to use for the intellisense to recognize them.  But I still get the same Error on building.
@using global::Blazor.Extensions
@using global::Blazor.Extensions.Canvas
@using global::Blazor.Extensions.Canvas.WebGL
