### ISSUE TITLE
Can we handle WebGL from js interop to wasm interop?

### ISSUE THREAD

**Issue by Kation** [BlazorExtensions/Canvas#42]
I think it will be much faster than now.
I'm searching WebAssembly with WebGL but found less information.
I hope there is a way to do this.

**Comment by GeorgeS2019** [comment]
Perhaps this [discussion](https://github.com/mono/SkiaSharp/issues/750) may be relevant.

**Comment by galvesribeiro** [comment]
There is a plan to bring Skia to WASM. Even if that becomes stable/released, I think it is subject for another project. I could definitively think of creating `Blazor.Extensions.Skia` but I wouldn't add support here. This project is strictly binding the HTML5.

I think there is not much todo here so I'm going to close the issue. If you think differently feel free to reopen with other options.

Thank you!

**Comment by GeorgeS2019** [comment]
Blazor.Extensions.Skia will be a game changer!!!!
