### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by heddle** [BlazorExtensions/Canvas#43]

**Comment by heddle** [comment]
Update:
Installed powershell on mac so I tried the Install-Package command and got:

****PS /Users/heddle/blazorApps/CanvasDemo/CanvasDemo> Install-Package Blazor.Extensions.Canvas

The package(s) come(s) from a package source that is not marked as trusted.
Are you sure you want to install software from 'MyNuGet'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
Install-Package : Unable to find dependent package(s) (Microsoft.AspNetCore.Blazor)
At line:1 char:1
+ Install-Package Blazor.Extensions.Canvas
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (Microsoft.AspNetCore.Blazor:String) [Install-Package], Exception
+ FullyQualifiedErrorId : UnableToFindDependencyPackage,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage****
 


Any help is appreciated!

**Comment by galvesribeiro** [comment]
Closing as there is no descriptions.
