### ISSUE TITLE
Repo test project not work in VS16.3.1

### ISSUE THREAD

**Issue by MikiraSora** [BlazorExtensions/Canvas#47]
![image](https://user-images.githubusercontent.com/7549173/66380117-57ba7500-e9e9-11e9-86ac-4417d28bb648.png)
![image](https://user-images.githubusercontent.com/7549173/66380233-96502f80-e9e9-11e9-90c6-ddc480af7dbc.png)
build&run from [commit](https://github.com/BlazorExtensions/Canvas/commit/1d59be9a2877651e413fb187b731f80d32f3d711)

**Comment by GeorgeS2019** [comment]
I by pass this problem using first dotnet to create Blazor Client project and then open this with VS16.3.1 and use nuget to install Blazor Canvas 0.4 and use the test codes provided in this repository to test both Canvas2D and WebGL functionalities.
