### ISSUE TITLE
Nuget - Blazor.Extensions.Canvas.JS Dependency does not exist

### ISSUE THREAD

**Issue by xforever1313** [BlazorExtensions/Canvas#7]
In 1.2, these were the following Nuget dependencies:
- Microsoft.AspNetCore.Blazor.Browser (>= 0.3.0)
- Microsoft.AspNetCore.Blazor.Build (>= 0.3.0)

However, in 1.3, the Nuget dependencies are now this:
 - Blazor.Extensions.Canvas.JS (>= 0.1.3)
 - Microsoft.AspNetCore.Blazor.Browser (>= 0.4.0)
 - Microsoft.AspNetCore.Blazor.Build (>= 0.4.0)

Blazor.Extensions.Canvas.JS does not appear to exist.  Trying to access it with [nuget.org](https://www.nuget.org/packages/Blazor.Extensions.Canvas.JS/) results in a 404 page.  Also, when trying to install the package via Nuget, the following error appears:

> Unable to find package Blazor.Extensions.Canvas.JS. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages, nuget.org

**Comment by galvesribeiro** [comment]
Sorry... I made a mistake while publishing the package.

I've published a new one https://www.nuget.org/packages/Blazor.Extensions.Canvas/0.1.4 but it will take a few minutes to get publicly available and indexed.

Please let me know if you face problems with it.

Thanks for reporting it!

**Comment by galvesribeiro** [comment]
I'm closing the issue as the new package is fixed. Thanks for reporting it!
