### ISSUE TITLE
Does not convert from clip space to screenspace

### ISSUE THREAD

**Issue by 2ndwolf** [BlazorExtensions/Canvas#70]
Using the following code should convert clip space into screen space and generate a 64x64 square at 0,0 but it doesn't. Cannot tell where it is actually drawing as I cannot get debuggers such as renderDoc to work.

```
        await GL.ViewportAsync(0, 0, 500, 500);

        float[] matrix = await M4.Computations.Orthographic(0, 500, 500, 0, -1, 1);
        matrix = await M4.Computations.Translate(matrix, 0, 0, 1);
        matrix = await M4.Computations.Scale(matrix, 64, 64, 1);

        await GL.UniformMatrixAsync(matrixLocation, false, matrix);
```

**Comment by jorolf** [comment]
Your code snippet is too small. Where do you setup your buffers and draw? Where is your shader code?

**Comment by 2ndwolf** [comment]
Terribly sorry, after a LOT of work I figured out the problem were my matrix transformations accepting integers instead of floats as parameters. At some point I thought the problem was glviewport not properly working but it is.
Closing this as it is not an issue with this extension. Thanks for the reply.
