### ISSUE TITLE
I need the canvas bounding client rectangle

### ISSUE THREAD

**Issue by dannypike** [BlazorExtensions/Canvas#76]
I want to be able to call ```getBoundingClientRect()``` on the ```<canvas>```, so that I can convert mouse coordinates into client coordinates. My instinct is to use JS Interop to do that, but the ```Id``` property is not public, so I am thinking that I will have to wrap the ```BECanvas``` in a ```<div>``` with an ```id``` that I can control, and then use look that up and get its child control.

This feels a bit convoluted to me. Is there a better way?

Perhaps you could make ```Id``` a public property?

**Comment by slango0513** [comment]
WebGLContext has Canvas.Id property. The problem is that <BECanvas> cannot register the ‘onmousedown’ event if we want to implement somthing like free drawing

**Comment by sonicmouse** [comment]
You could write an extension to get the `Id` of the canvas:

	public static class BECanvasExtensions
	{
		public static string GetHtmlId(this BECanvas beCanvas)
		{
			var field = typeof(BECanvas).GetField("Id", BindingFlags.Instance | BindingFlags.NonPublic);
			return field == null ? null : field.GetValue(beCanvas) as string;
		}
	}

**Comment by dannypike** [comment]
Thank you. Unfortunately, I've moved on to another project now, but I will try to remember that for next time!
