### ISSUE TITLE
BECanvas doesn't seem to work for .Net 5

### ISSUE THREAD

**Issue by rperazzolli** [BlazorExtensions/Canvas#94]
I'm migrating a project that worked fine in .Net 3.1 and, when trying to convert it to .Net 5 BECanvas, no longer works. The reference to BECanvasComponent remains null.

**Comment by mizrael** [comment]
I suspect this project has been abandoned.

**Comment by rperazzolli** [comment]
Thank you, mizrael. What would be the alternative you advise me to draw in Blazor with .Net 5?
In some projects with .Net 5 BECanvas seems to work fine, but in others it does not and I do not understand where the difference is.

**Comment by mizrael** [comment]
Honestly I don't have an alternative. I raised a PR a while ago, but got
no response. I even contacted both @galvesribeiro and @attilah , but they
didn't reply. I am considering creating a fork and publishing it on Nuget.

**Comment by rperazzolli** [comment]
The fault was exclusively mine.
The component is working properly. When translating code from Blazor Server 3.1 to Blazor WebAssembly 5, I made changes that affected the operation.
Thanks for your help.
