### ISSUE TITLE
Is there no support for getImageData (pulling pixels off the canvas)?

### ISSUE THREAD

**Issue by edhalsim** [BlazorExtensions/Canvas#97]
HTML5 supports this.  How can I read a block of pixels from the canvas?

**Comment by KristofferStrube** [comment]
Hey @edhalsim ,
The appropriate API is not exposed through this wrapper. I was working on doing this but wanted to have something that worked before engaging. My progress can be seen here. https://github.com/KristofferStrube/Canvas/tree/workGetImage . I might get around to making a pull request for this during this week.

**Comment by mizrael** [comment]
yeah I would love to see this included in the library.

**Comment by KristofferStrube** [comment]
@mizrael it doesn't seem like this repo is being updated anymore so I won't make the PR.

**Comment by mizrael** [comment]
I contacted the owners a while ago for a PR I raised. @attilah replied but I haven't heard from him since.

**Comment by attilah** [comment]
I finished updating the Logging to .NET 5.0, canvas is the next on the list, please bear with us ;-)

**Comment by Thaina** [comment]
@attilah This repo still alive?
